Feature/added storage parameter
keboola/python-component pull request #63
Opened 2024-07-25 12:47 UTC by kudj

added possibility to overwrite types support by variable in config: storage.output.data_type_support

2024-07-26 11:42 UTC, davidesner requested changes

2024-07-26 11:42 UTC, davidesner commented on src/keboola/component/interface.py
>          if not legacy_manifest:
Tohle cely bych dal do separe funkce pro detekci manifest typu kdyz uz je tam tolik podminek

2024-07-26 11:42 UTC, davidesner commented on src/keboola/component/dao.py
> +            if not legacy_manifest:
input manifest prece nemenime, tj. nema zadnou legacy variantu, nebo?

2024-07-26 11:42 UTC, davidesner commented on src/keboola/component/interface.py
>          if not legacy_manifest:
a dalsi vec Storage uz zpracovavame je to `TableOutputMapping` tam by se mel pridat ten `data_type_support`
a pak by se to dalo napsat hezceji: 
```python
legacy_manifest = self.configuration.tables_output_mapping.data_type_support or self.environment_variables.data_type_support
```

2024-07-26 11:49 UTC, davidesner commented on src/keboola/component/interface.py
>          if not legacy_manifest:
Jeste premyslim jak je tohle teda vymysleny? Co bude v `tables_output_mapping.data_type_support` pro existujici konfigurace. Tam prece nic neulozime pokud to user neulozi. Takze tam bude `null` ne? A potom `tables_output_mapping.data_type_support` bude vlastne vyplneny pokazdy. Ale jenom pro tu prvni vstupni komponentu, takze jak maji poznat processory co jsou dal, ze se celej ten chain ma chovat jako `none` ??

2024-07-26 12:22 UTC, kudj commented on src/keboola/component/dao.py
> +            if not legacy_manifest:
a jo, tady mě zmátly tyto testy: https://github.com/keboola/python-component/blob/803e18fdbf7f77c5687549c0477667b5c5bb2193/tests/test_dao.py#L152C4-L177C55

2024-07-29 08:45 UTC, davidesner approved these changes

2024-07-29 09:16 UTC, merged